### ISSUE TITLE
Error in List View

### ISSUE THREAD

**Issue by hephaestoskin** [opengeek/getCache#3]
The following snippet call creates the following error. Full calendar view works just fine. Using the most recent version of PHP. Recently there have been issues with depreciated code and syntax modifications with newer versions of PHP. This may be a result of that as the version of the site on my local machine works just fine.

[[!mxcalendar?
    &displayType=`list`
    &tplListItem=`listItemTpl`
    &tplListWrap=`listWrapTpl`
    &tplDetail=`detailTpl`
    &isLocked=`true`
    &resourceId=`6`
    &jqLibSrc=``
    &addJQ=`FALSE`
    &limit=`5`
]]

Error:

Warning: array_multisort() [function.array-multisort]: Argument #1 is expected to be an array or a sort flag in /home/content/75/8574375/html/tiesrev/core/cache/includes/elements/modsnippet/59.include.cache.php on line 283
No Events

**Comment by opengeek** [comment]
This is for the mxcalendar extra, not getCache unless I am missing something?

**Comment by hephaestoskin** [comment]
Yes actually, I seem to have made a late night mistake lol. I will close it.
