### ISSUE TITLE
Custom cache refresh menu problem

### ISSUE THREAD

**Issue by davidpede** [opengeek/getCache#6]
I have followed this guide: https://github.com/opengeek/getCache/wiki/Refresh-Custom-Cache-Partitions but am having issues with what I think is a js conflict within the manager.

My custom partition is caching correctly. I have setup a custom Menu using the guide above to clear it from the manager menu. I have placed it as a child of the Site --> Clear Cache menu as suggested.

When on the dashboard page of the manager, the custom menu works fine. Shows the console and clears the partition. However, when I am editing a resource and click on the custom menu the whole page breaks. The cache partition does not clear. There is no error in the log.

Has anyone experienced this or able to explain how to resolve? I love the feature but can't pass on to the client with this happening.

Using:
MODX Revo 2.2.12 Advanced (Same issue in 2.2.11)
getCache 1.1.0-pl

Thanks

Please see: http://forums.modx.com/thread/89231/getcache---custom-cache-refresh-menu-problem#dis-post-490716

**Comment by opengeek** [comment]
I think this may end up being a bug for modxcms/revolution in regards to setting the console logging topic. Needs research.

**Comment by davidpede** [comment]
Jason, have found the cause and it was a legacy context setting that caused the problem not a bug.

[[++assets_url]] had been changed to the top level domain name by a prev dev and it was interferring with the path to /assets/components/getcache/connector.php.

Once removed all works as planned. Thanks for a great snippet!
